import random
from Automation.speech import prntdisp
def greet_user():
    greetings = [
        "Good to see you! Welcome back!",
        "Hi, I’m online and ready to assist.",
        "Hello! I’m online now. What can I do for you?",
        "Welcome! I'm here and online, ready to help.",
        "Hey there! My status is online and I’m ready.",
        "Hello, I’m online and happy to assist!",
        "I’m available online—ready whenever you are!",
        "Hi there! I’m online and at your service.",
        "Welcome! I’ve gone online and I’m ready to help.",
        "Hi, I’m online and standing by for your instructions.",
        "Hello! I’m online, ready to provide assistance.",
        "I’m online now! Ready to help with whatever you need.",
        "Hi, I’m online and fully prepared to help you.",
        "Welcome back! I’m online and here to assist.",
        "I’m online and at your service. How can I help?",
        "Hey! I’m online and ready to take on any task.",
        "I’m online, ready and eager to assist you.",
        "I’m online, ready to serve and support you!",
        "Welcome! I’m online and available for your commands.",
        "Hello, I’m online and ready to execute your requests.",
        "I’m online and here to help—just let me know what you need.",
        "Hi there! I’m online and ready to tackle any tasks you have.",
        "I’m online, and ready to assist with anything you need!",
        "Welcome, I’m online and prepared to help you now.",
        "I’m online and standing by, waiting for your instructions.",
        "Hello! I’m online, ready to help you with any task.",
        "Hi! I’m online and at your disposal for whatever you need.",
        "Hello, I’m online and at your command.",
        "I’m online, ready for any action you need me to take.",
        "Hi, I’m online and ready to assist with whatever comes next.",
        "Welcome back! I’m online and ready to get started.",
        "I’m online and waiting to help with your next request.",
        "I’m online now, and ready to help with anything you need.",
        "I’m online and ready to support your needs.",
        "Hello! I’m online and here to assist you.",
        "Welcome! I’m online and available for your tasks.",
        "Hi, I’m online, here to serve you.",
        "I’m online and standing by to assist with anything you need.",
        "Hello! I’m online and available to assist with your next task.",
        "Hi! I’m online and ready to follow your instructions.",
        "I’m online, and ready for anything you need me to do!",
        "Welcome! I’m online and here to help with whatever you need.",
        "I’m online and ready to execute any task you give me.",
        "I’m online, and standing by to help you with your tasks.",
        "I’m online, and here to assist with your every need.",
        "Hi! I’m online and ready to take on anything.",
        "Welcome back! I’m online and here to help you now.",
        "I’m online, and ready to follow your every command.",
        "Hello, I’m online and prepared to assist you immediately.",
        "Hi! I’m online and ready to assist in any way I can.",
        "Welcome! I’m online, and ready to take your requests.",
        "I’m online and ready to assist you—just say the word!",
        "I’m online and at your service, ready to help.",
        "Hi there! I’m online and standing by for your commands.",
        "I’m online, ready to help however I can.",
        "Hello! I’m online and ready to support you."
    ]
    greeting = random.choice(greetings)
    prntdisp(greeting)

